import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/landingPage/Header";
import Footer from "./components/landingPage/Footer";
import Announcement from "./components/landingPage/Announcement";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={inter.className}>
        <div className="flex flex-col min-h-[100dvh]">
          <Announcement />
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
