export const randomAuthorName: string[] = [
  "Köşedeki Dörtlü Yakan Şahinci",
  "Kardeş Para Üstü Bozuk Yok",
  "Taksiyle Ters Şeride Giren Abi",
  "Halı Saha Messi'si",
  "Yavaşlayan Makasçı",
  "Düğünde Taklit Yapan Çiçekçi",
  "Kredi Kartını Tek Çeken Esnaf",
  "Sinyalsiz Dönen Doblo Sahibi",
  "Yanlış Anons Yapan Otobüs Şoförü",
  "Sınav Günü Uyuyakalan Öğrenci",
  "Cebinden Kalem Çıkarmayan Tüccar",
  "Yokuş Aşağı El Freni Çeken",
  "Her Yemekte 'Aç mısın?' Diye Soran Teyze",
  "Son Dakikada Gelip Tahtayı Sildiren Öğretmen",
  "Bayramda Telefon Açmayan Hala",
  "'Yan Koltukta Oturur Musun?' Diye Rica Eden Amca",
  "Zile Basıp Kaçan Mahalle Çocuğu",
  "Dörtlü İle Park Eden Pikap",
  "Hesabı 'Sonra Öderiz' Diyen Arkadaş",
  "Arabayı Sabah Camında Bırakan Kapıcı",
  "'Anında Bloklayan' Whatsapp Grubu Yöneticisi",
  "Otobüste Cam Kenarını Kapan Öğrenci",
  "Uzaktan Kumanda Kaybettiren Çocuk",
  "Sürekli Sessizde Oynayan Mahalle Halı Saha Takımı",
  "'Hayırlı Olsun' Demeden Elini Sıkmayan Düğün Misafiri",
  "İki Dakika Geciken Dolmuşçu",
  "Cepte Hep 5 Kuruş Bulunduran Taksici",
  "Apartman Önüne Ayakkabı Dizip Gitmeyen Komşu",
  "Çekilişte Hep Hediye Kazanan Şanslı",
  "Kavşakta Korna Çalmadan Duramayan Şoför",
  "Pazarda En Ucuz Domatesi Arayan Teyze",
  "Sürekli Şarjı Bitmiş Telefonu Olan Genç",
  "'Ben Bunu Yapmıştım' Diye Her Şeye Atlayan",
  "Birdenbire Fren Yapan Taksi Şoförü",
  "Evde Israrla Çay İstemeyen Misafir",
  "Kırmızı Işıkta Koşan Simitçi",
  "Alt Komşudan Şikayetçi Üst Komşu",
  "Daima Arka Sıraya Oturan Sınıf Başkanı",
  "Düğün Konvoyunda Korna Çalan Damat Arkadaşı",
  "Sürekli Kablosunu Kaybeden Şarj Cihazı Sahibi",
  "Mahallede Herkesin Amcası Olan Adam",
  "Yokuşta Araç Kaydıran Şoför",
  "Balkondan Herkese Karışan Teyze",
  "Sabahın Köründe Matkap Açan Komşu",
  "Düğünde Sahneye Fırlayan Oynak Dayı",
  "Hava Durumuna Her Zaman Yanılan Meteorolog",
  "Her Yerde Yanlış Park Eden Sürücü",
  "Marketin Kapanış Saatinde Giren Müşteri",
  "Telefonu Sürekli Sessizde Unutan Genç",
  "Vapurda Simit Martıya Atan Turist",
  "Taksimetreyi Çaktırmadan Açan Taksi Şoförü",
  "Otobüste Son Anda İnmek İsteyen Yolcu",
  "Piknikte Mangal Dumanını Herkese Yayan Aile",
  "Düğün Pastasını İndiren Dayı",
  "İki Kuruşa Pazarlık Yapan Pazar Teyzesi",
  "Halı Saha Gol Sevincinde Formayı Çıkaran Adam",
  "Serpme Kahvaltıyı Bitiremeyen Grup",
  "Şampiyon Olmadan Meydanlara Dönen Taraftar",
  "Tatilde Güneş Kremi Sürmeyi Unutan Tatilci",
  "Yanlış WhatsApp Grubuna Mesaj Atan Amca",
  "Ters Yöne Giren Otobüs Şoförü",
  "Saat 22:00'de Bahçede Havai Fişek Atan Komşu",
  "Aynı Şarkıyı Defalarca Çalan Taksi Radyosu",
  "Piknik Alanında Mangalı İyi Yakmayan Abi",
  "Son Çayı İçen İş Arkadaşı",
  "Şeker Bayramında Çocukları Boş Çeviren Teyze",
  "Dondurma Çubuğunu Yanlış Taraftan Açan Genç",
  "Futbol Maçında Kaleciyi Geçen Topu Kovalamayan Oyuncu",
  "Haftasonu AVM'yi Talan Eden Aile",
  "Oyun Konsolunda Sürekli Yenilen Çocuk",
  "Açık Büfede Tabağı Doldurup Yarım Bırakan Tatilci",
  "Eve Kapanan Kışlıklarını Arayan Teyze",
  "Tatilde Havuz Başında Kitap Okuyup Yanan Abi",
  "Plajda Mısır Satarken Dans Eden Satıcı",
  "Halı Sahada Sürekli Topu Kalenin Üstüne Atan Forvet",
  "Düğünde Sahneye Fırlayıp Oyunbozanlık Yapan Dayı",
  "Telefonun Kablolu Kulaklığını Sürekli Dolaştıran Genç",
  "Vapurda Çay Bardağını Sallandırarak Boşaltan Yolcu",
  "Pazar Fileleriyle Koşan Çocuk",
  "Bakkala Ekmek Almaya Gidip Dönmeyen Çocuk",
  "Otobüste Sürekli Arka Kapıyı Açtırmaya Çalışan Yolcu",
  "Kışın Balkonda Donmuş Çamaşır Toplayan Anne",
  "En Arka Koltuktan Film Yorumlayan Sinema İzleyicisi",
  "Düğünde Oynamaya Zorlanan Baba",
  "Her Bayram Sonrası 'Sen Büyümüşsün' Diyen Teyze",
  "Kapalıçarşı'da Turist Kovalayan Satıcı",
  "Halı Sahada Hiç Koşmayan Kaleci",
  "Koltukta Uyuyakalan Misafir",
  "Gece Gece Sesli Kahkaha Atan Komşu",
  "Her Fırsatta Gömlek Çıkartan Halı Saha Abisi",
  "Elinde Sürekli Tespih Sallayan Genç",
  "Bayramda Torpil Atmaya Çalışan Mahalle Çocuğu",
  "Yazlıkta Mangalı Hep Yakan Abi",
  "Sabahın 6'sında Denize Koşan Tatilci",
  "Sürekli 'Hayırdır?' Diyen Mahalle Delikanlısı",
  "Evde Kendi Kendine Oyun Oynayan Çocuk",
  "Dolmuşta Müziği Sonuna Kadar Açan Şoför",
  "Takım Elbiseyle Futbol Oynayan Amca",
  "Toplu İğneyi Kaybedip Evi Arayan Anne",
  "Kapının Önünde Yere Minder Atıp Oturan Komşu",
  "Kışın Sobanın Başında Mısır Patlatan Dede",
  "Otobüsün Arka Koltuğunda Sızan Yolcu",
  "Pikniğe Mangalsız Giden Aile",
];
